name: Prepare release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Development version"
        required: true
        default: "X.Y.Z-SNAPSHOT"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare release
        run: mvn -V -B release:prepare -DdevelopmentVersion=${{ developmentVersion }} -DreleaseVersion=${{ github.event.inputs.releaseVersion }}
