name: Prepare release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Development version"
        required: true
        default: "X.Y.Z-SNAPSHOT"
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - run: |
          git config --global user.name 'Cuong Tran'
          git config --global user.email 'ctran@users.noreply.github.com'

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare release
        run: |
          mvn -V -B -ntp release:prepare \
            -DpreparationGoals=validate \
            -DpushChanges=false \
            -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
            -DreleaseVersion=${{ github.event.inputs.releaseVersion }}

          git push --tags && git push